### ISSUE TITLE
Landcover input files

### ISSUE THREAD

**Issue by Mareena0409** [natel-c/lpjg-forestC-emulator#1]
Dear developer, 
I understand that this is an application level project of LPJ-GUESS and I am highly appreciative of you work. Mine is a basic issue and if you could help me or even connect me with someone who can help, it would be great!
I am trying to run the land cover module of LPJ-GUESS 4.1 version. Now I am trying to run with some demo land cover data prepared my myself for a single grid for six years from 1980-1985. However I am facing the error :

Removing mt TeSo_mt
[LPJ-GUESS Thu Dec 12 11:54:05 2024]

LPJ-GUESS cohort mode - global pfts
Problems with stand type fractions input file. EXCLUDING STAND at 94.000,28.500 from simulation.

Error: could not find stand at (94,28.5) in landcover/management data file(s)

Finished.

If you have any Idea about the reason for this error, please do help. Thank you for your time. I will attach a screenshot of the error and my demo land cover and management files for your reference.

![Screenshot 2024-12-12 115446](https://github.com/user-attachments/assets/89b33f5a-3ef1-497c-a598-888e39f7e8f9)
[lu_fractest.txt](https://github.com/user-attachments/files/18110659/lu_fractest.txt)-Land cover fraction input file
[cr_frac.txt](https://github.com/user-attachments/files/18110661/cr_frac.txt)-cropland st fraction input file
[man_frac.txt](https://github.com/user-attachments/files/18110663/man_frac.txt)-Managed forest st fraction input file
[nat_fractest.txt](https://github.com/user-attachments/files/18110665/nat_fractest.txt)-Natural st fraction input file
[pas_frac.txt](https://github.com/user-attachments/files/18110666/pas_frac.txt)-Pasture st fraction input file
[Nfert_st.txt](https://github.com/user-attachments/files/18110670/Nfert_st.txt)-N fertilisation rate input file (per st)

**Comment by natel-c** [comment]
Hello,
Thank you for reaching out and submitting your issue.
However, it seems that this issue is unrelated to this repository. Although the repository name includes "LPJ-GUESS", this project does not contain the LPJ-GUESS code, and the landcover module is not used here. This repo is for a ML Python emulator of the model.

I'd still be happy to assist you though. But please contact me directly at carolina.natel@gmail.com.

Since this issue is not related to this repository, I will be closing it now.

Best,
Carolina

**Comment by Mareena0409** [comment]
Hello Ms. Carolina,
Thank you so much for your reply and willingness to help. I will reach out
to you in person as you suggested.
Regards
Mareena Mathew
